void motor1_position1 ( void );
void motor1_position2 ( void );
void motor1_position3 ( void );
void motor1_position4 ( void );
void motor1_position5 ( void );
void motor2_position1 ( void );
void motor2_position2 ( void );
void motor2_position3 ( void );
void motor2_position4 ( void );
void motor2_position5 ( void );
void position_setup_motor1 ( uint8_t position );
void position_setup_motor2 ( uint8_t position );
void servo_motor1_left ( void );
void servo_motor1_right ( void );
void servo_motor2_left ( void );
void servo_motor2_right ( void );